### ISSUE TITLE
Investigate GeoServer slowdowns for Harris

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#17]
Harris has asked us to investigate on a slodown they are experiencing with serving NetCDF files.

They gave us a sample configuration with some data which can be downloaded [here](https://www.dropbox.com/s/9xbp7zvcpvdsmlj/geosolutionsPackage.tar.gz?dl=0).

Apparently they are seeing bad performances (as in making GS not responding) on largish WCS extractions in NetCDF format. They gave us also some sample requestes together with the data.

The discussion started from [this](https://geosolutions.freshdesk.com/helpdesk/tickets/15091) ticket.

Ask Simone for more details.

**Comment by aaime** [comment]
The situation is similar to the Eumetsat one. Took a while to setup their database/datadir, but once setup, I've found most of the time was spent querying the H2 database on coverage slice catalog initialization.
The original sample WCS query @wcsGetCovSample.xml) took 8-9 seconds.

The switched to using a geoserver managed datastore for the granule slice catalog (aka auxiliary datastore) and the same request went down to 3 seconds.

Now, the above improvement is:

- available only on master (was not a small set of changes and included new features in mosaic and netcdf, like using the Repository interface and associated properties to configure it)
- it has been done in february while the 2.13.0 was being created (but on the master branch)
- could be backported now, we'll have some extra difficulties due to the "whole codebase reformat" 

Note, the file keeps on being opened multiple times, what we shaved off above was over 90% of the opening time. The reason for doing this is thread safety, we cannot guarantee the NetCDF image reader and the underlying library are thread safe, and the mosaic can go MT.

We also need to understand which version is Harris using, and to which one they might upgrade if needed, and if they are ok in storing in the postgresql database another schema to hold the netcdf lookup tables.

**Comment by aaime** [comment]
Ah, tickets for reference (assuming a backport to 2.13.x):
*  [GEOT-5822] Improve ImageMosaic's NetCDF performances
*  Possibly, but not sure, [GEOT-5939] NoData information lost when using NetCDF image mosaic with JAI imageread enabled Andrea Aime 05/02/18 17.33

**Comment by simboss** [comment]
Ok, let's wait for Harris feedback.

**Comment by simboss** [comment]
Let's explain them how to do this and then we stop.

@aaime wait for my next email before answering.

**Comment by aaime** [comment]
What do we do for this one now?

**Comment by simboss** [comment]
I am asking @Gnafu to take over this task for the moment.
