### ISSUE TITLE
Investigate additional requirements from Bayer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#19]
Questions from email after last week's meeting below.

We should go over them before starting the real work on Raster Algebra (RA from now) and report on Tue meeting.

**Comment by simboss** [comment]
Here are some additions to raster algebra topic, requested from BAYERr&d team:

 
1. Will it be possible to cut outliers based on 3 (or other number, 2 for example) [sigma](https://en.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule)  ?  Another article on this technique [here](https://www.investopedia.com/terms/t/three-sigma-limits.asp).  Three-sigma limit (3-sigma limits) is a statistical calculation that refers to data within three standard deviations from a mean.

2.  If we cut outliers – can we control with which data we fill cut pixels? Here we would like to have control on algorithm level, for example it can be specific interpolation algorithm that fills just created holes

3.  Will it be possible to run raster algebra analytics based on field boundary geometry, not bounding box?  Aim is to provide analytics for field boundary, excluding nearby roads, buildings and trees.

My feedback:
1. this could be a specific rendering transformation but it would be best to have a specific RA function
2. this is about no data and interpolation
3. this is about providing a ROI to the RA function. They have this ROIs outside GeoServer the will have to provide it somehow.

**Comment by aaime** [comment]
My feedback:

1. Indeed that would be a separate rendering transformation. I guess we'd need to run statistics and then perform the cut, if that's done after the algebra, we can hope the tiles are going to fit in the view
2. Filling by uniform value would be a parameter of the above RT, filling by "interpolation" is a different story, the cost can be high if the hole is expensive (even when using simple algorithms like IDW). I guess this would be a different RT again, and one that gets a ROI to operate on
3. Currently there is no way to pass an area of interest to a RT, they always operate on the BBOX, and the BBOX/resolution to read is decided by the renderer.. but we could have the first RT in the chain receive an area on which it operates and use [RenderingTrasformation#invertGridGeometry](https://github.com/geotools/geotools/blob/master/modules/library/main/src/main/java/org/geotools/filter/function/RenderingTransformation.java#L58). As an alternative, we could create new SLD parameters to control the renderer itself (would require proposal, but would not be limited to the particular RT that happens to be first in the chain having a parameter for the "area of interest").

A note about chaining rendering transforms. In the past we had issues with it, I cannot find open tickets right now, but I'd still be cautious about it, issues could arise

**Comment by aaime** [comment]
Btw, links for computing variance (needed for 3 sigma) in one pass (mind accuracy!):
* http://www.buluschek.com/?tag=mean
* https://www.strchr.com/standard_deviation_in_one_pass

**Comment by aaime** [comment]
Questions to ask:
* Do we need to compute the raster algebra before or after running the statistics? 
* Do we compute the statistics on entire field even if the view only partially intersects the field? (if not, the map will change due to different stats)
* What kind of interpolation should we use on "larger" holes (e.g, not single pixel, where a point interpolation algorithm approach would seem to make more sense?)

Thinking out loud, what about an approach in which we compute the stats in advance on the fully field using a WPS, on the entire field, and pass them to the on the fly WMS rendering as an env variable? This would allow to just filter the pixels in algebra, allowing for a shorter computation chain (compute values, fill holes).

For null filling, also see this (they do seem heavy, batch processing oriented algorithms though): https://grass.osgeo.org/grass74/manuals/r.fillnulls.html
