### ISSUE TITLE
Illustreets GS Development - New spatial predicate

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#27]
See proposal for Manuel Timita.

**Comment by aaime** [comment]
From the mail thread:
* We want to have a NEAREST spatial predicate in ECQL, with the usage being something similar to  ``NEAREST(geom_column,POINT(21707 6558912),10)``, returning the nearest 10 features to POINT. Hopefully, where the database provides optimisations (e.g. PostGIS true KNN), that can be used.
* To be implemented as a special filter function like done in Oracle, see [function](https://github.com/geotools/geotools/blob/865cc72a90b07841a4c871d1b07fcc8e5defd35b/modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/filter/function/FilterFunction_sdonn.java#L30) and SQL translation (https://github.com/geotools/geotools/blob/865cc72a90b07841a4c871d1b07fcc8e5defd35b/modules/plugin/jdbc/jdbc-oracle/src/main/java/org/geotools/data/oracle/OracleFilterToSQL.java#L206)
* Usage could look like `` cql_filter=my_col IN ('X', 'Y') AND pgNearest(POINT(16.36 48.205),30)=true AND my_other_col > 0  ?``

The implementation will assume postgis > 9.5 and availability of primary key and must turn the function into a subquery so that we can express that as part of the where clause (encoding it as part of the top level order would require too many code changes with broad consequences):

````
SELECT *
FROM theTable
where primaryKey in (
     select primaryKey 
     from theTable 
    ORDER BY geom <-> referenceGeometry limit numberOfItemsDesired;
) AND/OR other filters coming from the request
ORDER BY order available in the request
````

**Comment by simboss** [comment]
assigning to @fernandor777

**Comment by fernandor777** [comment]
Work in progress branch:
https://github.com/fernandor777/geotools/tree/nearest

Status: filter working, creating tests

**Comment by fernandor777** [comment]
PR on master:
https://github.com/geotools/geotools/pull/2169

Should we do backport for this new feature?

**Comment by simboss** [comment]
I have assigned the review of this to @aaime

**Comment by aaime** [comment]
Review done

**Comment by fernandor777** [comment]
Thanks @aaime

**Comment by fernandor777** [comment]
I did some changes, please @aaime  could you look at them?

**Comment by fernandor777** [comment]
PR merged on master branch.
