### ISSUE TITLE
Investigate impact of switch to JAI-Ext as default

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#41]
We should investigate and estimate the extent of the changes to be performed to make the switch happen.

**Comment by aaime** [comment]
I've looked at enabling jai-ext by default, by running builds and disabling failing tests, to get a "size" of the activity.

GeoTools changes: https://github.com/aaime/geotools/commit/dbde5b55ae36b8d0914df05a5398c681c1226f19
GeoServer changes: https://github.com/aaime/geoserver/commit/24234b376827f60865c46359b79e2d18452850e4

For GeoServer there was a test that needed to be updated, but was a quick fix, for GeoTools there are a couple of tests marked as @Ignore because they are rendering with a gray background, and that gray is given to the mosaic operation, which turns it into black... looks like a "background is nodata" assumption issue.

![Selezione_503.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57f7dd711b9ffe0e00024f89/125516c66e82c728ace21e0d46db919626988aa681ec8016f40eb2d86b56357c2301a03f32dfa17de6472c560d0d1ffe14595c4dadf9882df0e73821db5c0effcd7f1d2598694ef1e1c84afd13b0328a488fb7b98e4bc6ed3825e7838f4d370c48.png)

Long short short, it seems that we have one jai-ext bug to fix (could also be due to the way we call onto jai-ext). I don't have a firm estimate, but I'd guess a day  to fix it, if it has not too many ramifications.
