### ISSUE TITLE
Estimate needed to revamp, clean up and contribute ESRI Rest Services Implementation for GeoServer

### ISSUE THREAD

**Issue by simboss** [geosolutions-it/aaime#70]
[GeoServer GSR Extension Status.pdf](https://github.com/geosolutions-it/aaime/files/3258842/GeoServer.GSR.Extension.Status.pdf)
I have been talking with [ODC](https://www.pdc.org/) and their former employee Jeff Smith from GeoSpago about this subject. We need to come up with an estimate as funding is available for this work to happen.

The latest exchange I have had with Jeff follows:
> I have attached a presentation that I created for PDC which outlines the current status of the GSR extension.  As I mentioned on the call, Boundless originally had the GSR extension in their geoserver-exts repo on GitHub (https://github.com/boundlessgeo/geoserver-exts), but on November 18, 2015 they removed it with the comment "Remove GeoServices REST API to separate repo".  There was no additional info on what "separate repo" or where the project was moved.

> Luckily, I was able to find a repo called GSR which was created by the Boundless employee John Schulz on December 1, 2017.  In this repo the extension was upgraded to work with GeoServer 2.13 and it looks like work was done to allow feature create, update, and delete capabilities.  I had mentioned on the call that I thought there were some unmerged changes from here https://github.com/ROGUE-JCTD/geoserver-exts, but on second review I think I was mistaken and John Schulz's repo does have the latest.

> In regards to licensing, in John Schulz's repo most files still have the header "This code is licensed under the GPL 2.0 license, available at the root application directory".  However, any new classes he added are missing this message in the header, and unfortunately there is no license available at the root of the repo.  I know the GPL license is copyleft in nature, but I'm not an expert open source licensing so I am not sure if this means we can use this code or not.

> Let me know if you have any questions and feel free to connect me with Andrea directly if it is helpful.  I look forward to hearing back from you and setting up a call to discuss next steps._[Uploading... GeoServer GSR Extension Status.pdf ]

The baseline goal is to clean this up, make it work with latest geoserver ( I would say 2.15 also if possible)  for their use cases (see presentation).
I would not mind seeing a plan that include improvements to the core + missing functionalities. 
They seem to have money now to spend so we can grab them quickly and do a good job that does not stop at making this work but also goes beyond and touches adding missing bits and improving things that are already there.

**Comment by aaime** [comment]
The licensing bit is not trivial given that contributing code to GeoServer one needs a CLA written by the contributor. It works clearly when the writer donates the code, otherwise I'm not sure. 
The CLA is there to allow switch licenses (which we did, the GeoServer license is a modified GPL, which we changed a couple of times to allow otherwise incompatible dependencies like EMF and XSD).

**Comment by aaime** [comment]
Checked the code, it's nothing special and should be easy enough to migrate to GeoServer 2.15.x. A large bunch of it it's model objects for Jackson to translate to JSON and back, the controllers seem easy enough. 

There are some parts I don't understand in the implementation, and the specification of the API seems to be almost 10 years old:
https://www.esri.com/library/whitepapers/pdfs/geoservices-rest-spec.pdf

The current documentation can be found here, for the map service and feature service (check carefully the tree on the side, it has a lot of sub-resources for each of these two):

- https://developers.arcgis.com/rest/services-reference/feature-service.htm
- https://developers.arcgis.com/rest/services-reference/map-service.htm

The controllers have also a "relationship service" published at "/gsr/relationships/{workspaceName}" that I cannot find documentation for in the ESRI services API.

**Comment by aaime** [comment]
@simboss do we need any more work on this ticket, or can the estimate be considered "done"?

**Comment by aaime** [comment]
Found some demo servers with a bunch of services, e.g. http://sampleserver3.arcgisonline.com/ArcGIS/rest, with sampleserverN and N going from 1 to 6.

Quick reference of instances:
- MapServer at http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/HomelandSecurity/operations/MapServer (and many others)
- FeatureServer at http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/HomelandSecurity/operations/FeatureServer 
- ImageServer at http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Earthquakes/CaliforniaDEM/ImageServer and http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Earthquakes/SanAndreasLidar/ImageServer

**Comment by aaime** [comment]
Checked the code coverage for GSR, it's pretty high, not sure there are many tests to add:

![image](https://user-images.githubusercontent.com/325433/60027197-49945300-969d-11e9-80fa-b0646e33f787.png)

**Comment by aaime** [comment]
Documentation wise, even the suite had pretty much nothing, just half a page with pointers.
The web site has been taken down, but the wayback machine has something:

https://web.archive.org/web/20180714205327/http://suite.opengeo.org/docs/latest/intro/extensions.html#geoservices-rest-api
https://web.archive.org/web/20180707042240/http://suite.opengeo.org/docs/latest/sysadmin/gsr/index.html

**Comment by aaime** [comment]
In terms of what is implemented, I've taken a peek at https://github.com/ROGUE-JCTD/geoserver-exts/blob/master/gsr/feature-parity.md and updated a bit.

General limitations:

- The ESRI GeoServices have HTML and JSON, GSR only has JSON (the HTML representation allows browsing around and building operations, e.g., see a [map building example](http://sampleserver1.arcgisonline.com/ArcGIS/rest/services/Demographics/ESRI_Census_USA/MapServer/export?bbox=-207.682974279982%2C-8.91646882718841%2C-37.1804225764967%2C98.2039461944433&bboxSR=&layers=&layerdefs=&size=&imageSR=&format=png&transparent=false&dpi=&time=&layerTimeOptions=&f=html))
* GSR handles where filters as ECQL, while they are SQL instead (similar, but not same)

[Map Service](https://developers.arcgis.com/rest/services-reference/map-service.htm) comparison:
  * All layers and tables. Supported.
  * Attachment. Not supported.
  * Attachment info. Not supported.
  * Dynamic Layer/Table. Not supported.
  * Estimate export tile size. Not supported.
  * Export map. Not supported.
  * Export tiles. Not supported.
  * Service extension. Not supported.
  * Feature (dynamic layer). Not supported.
  * Feature (layer). Not supported.
  * Find. Not supported.
  * Generate KML. Not supported.
  * Generate renderer (Dynamic layer). Not supported.
  * Generate renderer (Layer). Not supported.
  * HTML Popup (Dynamic layer). Not supported.
  * HTML Popup (Layer). Not supported.
  * Identify. Not supported.
  * Image. Not supported.
  * KML Image. Not supported.
  * Layer/Table. Supported.
  * Legend. Supported.
  * Map tile. Not supported.
  * Map service input. Not supported.
  * Map service job. Not supported.
  * Map service result. Not supported.
  * Query (Dynamic layer.) Not supported.
  * Query (Layer.) Supported.
  * Query related records (Dynamic layer.) Not supported.
  * Query related records (Layer.) Not supported.
  * WMTS. Not supported. (GeoServer does support this, but via GeoWebCache integration rather than the GeoServices extension.)
  * WMTS Capabilities. Not supported. (GeoServer does support this, but via GeoWebCache integration rather than the GeoServices extension.)
  * WMTS Tile. Not supported. (GeoServer does support this, but via GeoWebCache integration rather than the GeoServices extension.)

**Comment by aaime** [comment]
In terms of [styling comparison](https://developers.arcgis.com/documentation/common-data-types/renderer-objects.htm):

- All renderers lacks rotation support (rotationType/rotationExpression), we could add it
- SimpleMarkerSimple lacks esriSMSTriangle, we can add it
- In SimpleFillSymbol esriSFSHorizontal is missing. Anything but solid fill is actually not translated, we could add it recognizing the well known marks used to do hatch marks.
- Labelling information does not appear to be emitted, although there is code to generate that symbology (probably never tested though)
- Creation of class breaks renderer does not support PropertyIsBetween, could be added

Going to turn the above into into estimates.

**Comment by aaime** [comment]
So the estimate is complete, shall I close this ticket?

**Comment by simboss** [comment]
y
